max_width = 100
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
edition = "2021"
struct_lit_width = 40
fn_params_layout = "Tall"
fn_call_width = 60
use_field_init_shorthand = true
